server:
  port: 8081

web:
  domain: http//localhost
#  解决循环注入
spring.main.allow-circular-references: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hzz
    url: jdbc:mysql://localhost:3306/campus_v1
    type: com.zaxxer.hikari.HikariDataSource
#设置：在控制台显示查询数据库时所用到的 sql 语句
logging:
  level:
    root: info
    com.hzz.campusrear: info
